name: signposts
description: A flutter plugin for Apple's os_signpost API.
version: 0.0.1
repository: https://github.com/gaaclarke/signposts

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.11.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^1.2.1
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  ffigen: ^4.1.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
